-- Migration: move group membership from Article to ArticleVariant
-- Groups now contain variants, not parent articles.

-- 1. Remove group fields from Article
ALTER TABLE "Article" DROP COLUMN IF EXISTS "groupSelectorValue";
ALTER TABLE "Article" DROP COLUMN IF EXISTS "groupOrder";

-- Drop FK constraint on Article.groupId before dropping the column
-- (constraint name generated by Prisma: Article_groupId_fkey)
ALTER TABLE "Article" DROP CONSTRAINT IF EXISTS "Article_groupId_fkey";
DROP INDEX IF EXISTS "Article_groupId_idx";
ALTER TABLE "Article" DROP COLUMN IF EXISTS "groupId";

-- 2. Add group fields to ArticleVariant
ALTER TABLE "ArticleVariant" ADD COLUMN IF NOT EXISTS "groupId"            TEXT;
ALTER TABLE "ArticleVariant" ADD COLUMN IF NOT EXISTS "groupOrder"         INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ArticleVariant" ADD COLUMN IF NOT EXISTS "groupSelectorValue" TEXT    NOT NULL DEFAULT '';

-- 3. Add FK from ArticleVariant.groupId -> ArticleGroup.id (SET NULL on delete)
ALTER TABLE "ArticleVariant"
  ADD CONSTRAINT "ArticleVariant_groupId_fkey"
  FOREIGN KEY ("groupId") REFERENCES "ArticleGroup"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;

-- 4. Index for groupId on ArticleVariant
CREATE INDEX IF NOT EXISTS "ArticleVariant_groupId_idx" ON "ArticleVariant"("groupId");
